version: '3.8'

services:
  database:
    container_name: database
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8888:8080
    links:
      - database
    restart: always
